import { testFindMany } from "./read/testFindMany";
import { testFindFirst } from "./read/testFindFirst";
import { testCount } from "./read/testCount";
import { testInclude } from "./read/testInclude";
import { testIncludeAdvanced } from "./read/testIncludeAdvanced";
import { testAggregate } from "./read/testAggregate";
import { testGroupBy } from "./read/testGroupBy";
import { testGroupByHaving } from "./read/testGroupByHaving";
import { testWhereRelation } from "./read/testWhereRelation";
import { testWhereOneToOneNull } from "./read/testWhereOneToOneNull";
import { testCursor } from "./read/testCursor";
import { testGlobalOmit } from "./read/testGlobalOmit";
import { testFilterConditions } from "./read/testFilterConditions";
import { testOrderByAdvanced } from "./read/testOrderByAdvanced";
import { testTakeNegative } from "./read/testTakeNegative";
import { testFields } from "./read/testFields";
import { testIgnore } from "./read/testIgnore";
import { testMap } from "./read/testMap";
import { testIgnoreSheets } from "./read/testIgnoreSheets";
import { testMapSheets } from "./read/testMapSheets";
import { testEnumConstants } from "./read/testEnumConstants";
import { testFindManyDb2 } from "./read/testFindManyDb2";
import { testSelectRelation } from "./read/testSelectRelation";
import { testSelfRelation } from "./read/testSelfRelation";
import { testRelationOmitFalse } from "./read/testRelationOmitFalse";
import { testGetColumnHeaders } from "./read/testGetColumnHeaders";
import { testZeroMatch } from "./read/testZeroMatch";
import { testDistinctOrderByMulti } from "./read/testDistinctOrderByMulti";
import { testCountZeroRelation } from "./read/testCountZeroRelation";
import { testIncludeNull } from "./read/testIncludeNull";
import { testDateFilter } from "./read/testDateFilter";
import { resetAllSheets } from "../reset/resetAllSheets";

function testRead() {
  resetAllSheets();
  testFindMany();
  testFindFirst();
  testCount();
  testInclude();
  testIncludeAdvanced();
  testAggregate();
  testGroupBy();
  testGroupByHaving();
  testWhereRelation();
  testWhereOneToOneNull();
  testCursor();
  testGlobalOmit();
  testFilterConditions();
  testOrderByAdvanced();
  testTakeNegative();
  testFields();
  testIgnore();
  testMap();
  testIgnoreSheets();
  testMapSheets();
  testEnumConstants();
  testFindManyDb2();
  testSelectRelation();
  testSelfRelation();
  testRelationOmitFalse();
  testGetColumnHeaders();
  testZeroMatch();
  testDistinctOrderByMulti();
  testCountZeroRelation();
  testIncludeNull();
  testDateFilter();

  Logger.log("🎉 All read tests passed!");
}

export { testRead };
