const tagData = [
  ["id", "name"],
  [1, "JavaScript"],
  [2, "TypeScript"],
  [3, "React"],
  [4, "Next.js"],
  [5, "Node.js"],
  [6, "Python"],
  [7, "Rust"],
  [8, "Go"],
  [9, "Docker"],
  [10, "Kubernetes"],
  [11, "AWS"],
  [12, "GCP"],
  [13, "Azure"],
  [14, "GraphQL"],
  [15, "REST"],
  [16, "SQL"],
  [17, "NoSQL"],
  [18, "CSS"],
  [19, "HTML"],
  [20, "Git"],
  [21, "テスト"],
  [22, "CI/CD"],
  [23, "セキュリティ"],
  [24, "パフォーマンス"],
  [25, "アーキテクチャ"],
  [26, "機械学習"],
  [27, "データサイエンス"],
  [28, "DevOps"],
  [29, "モバイル"],
  [30, "クラウド"],
];

export { tagData };
